# Generated by Django 3.1.7 on 2021-05-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20210508_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='short_name',
            field=models.CharField(default='ps4', max_length=120),
            preserve_default=False,
        ),
    ]
