# Generated by Django 3.1.7 on 2021-05-04 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelisting',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamelisting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='savedgamelisting',
            name='game_listing',
        ),
        migrations.RemoveField(
            model_name='savedgamelisting',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
