# Generated by Django 3.1.7 on 2021-05-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210504_0141'),
        ('game', '0002_auto_20210504_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameListing',
        ),
        migrations.DeleteModel(
            name='SavedGameListing',
        ),
    ]
