# Generated by Django 3.1.7 on 2021-05-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('full_name', models.CharField(max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('calling_code', models.CharField(blank=True, max_length=5, null=True)),
                ('region_code', models.CharField(blank=True, max_length=5, null=True)),
                ('sub_region_code', models.CharField(blank=True, max_length=5, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_decimals', models.CharField(blank=True, max_length=5, null=True)),
                ('iso2', models.CharField(blank=True, max_length=5, null=True)),
                ('iso3', models.CharField(blank=True, max_length=5, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capital', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['state', 'name'],
            },
        ),
    ]
