# Generated by Django 3.1.7 on 2021-05-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('console', '0003_auto_20210505_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to=settings.AUTH_USER_MODEL),
        ),
    ]
